### PR TITLE
Dependeces are corrected

### PR DESCRIPTION
**Pull request by ariain**

### CODE REVIEW

**Comment by jainthedestroyer** [comment]
I signed it!

**Comment by jainthedestroyer** [comment]
I signed it!

**Comment by jainthedestroyer** [comment]
I signed it!

**Comment by jainthedestroyer** [comment]
done

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Pull request closed without merging**
